defaults: &defaults
  steps:
    - run:
        name: Ensure npm is at least at version 3
        command: |
          if [[ "$(npm --version)" = [12].* ]]; then
            npm install --global npm@3
          fi
    - checkout
    - run:
        name: Install and test
        command: |
          npm install --loglevel warn
          npm test --loglevel warn

version: 2
jobs:
  node4:
    docker:
      - image: library/node:4
    <<: *defaults
  node6:
    docker:
      - image: library/node:6
    <<: *defaults
  node8:
    docker:
      - image: library/node:8
    <<: *defaults

workflows:
  version: 2
  build_all:
    jobs:
      - node4
      - node6
      - node8
